[tox]
requires =
  tox>=4
  tox-uv
envlist =
  py312-{latest,min}-{unit,integration}
  py31{3,4}{,t}-{latest,pre}-{unit,integration}
  typecheck
  style
isolated_build = true

[gh-actions]
python =
  3.12: py312
  3.13: py313
  3.13t: py313t
  3.14: py314
  3.14t: py314t
  3.15: py315
  3.15t: py315t

[gh-actions:env]
DEPENDS =
  pre: pre
  latest: latest
  min: min

TEST =
  integration: integration
  unit: unit

[testenv]
description = Pytest with coverage
extras = bids
dependency_groups =
  test
  integration: datalad
# Not sure how to trigger an environment that only does the fetch :-/
commands_pre =
  integration: datalad get -J2 \
  integration:   tests/data/ds005365/sub-CISC13877/func/sub-CISC13877_task-rest_dir-AP_run-01_bold.nii.gz \
  integration:   tests/data/ds005365-fmriprep/sub-CISC13877/anat/sub-CISC13877_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 \
  integration:   tests/data/ds005365-fmriprep/sub-CISC13877/fmap/sub-CISC13877_run-01_fmapid-auto00000_desc-coeff_fieldmap.nii.gz \
  integration:   tests/data/ds005365-fmriprep/sub-CISC13877/fmap/sub-CISC13877_run-01_fmapid-auto00000_desc-epi_fieldmap.nii.gz \
  integration:   tests/data/ds005365-fmriprep/sub-CISC13877/fmap/sub-CISC13877_run-01_fmapid-auto00000_desc-preproc_fieldmap.nii.gz \
  integration:   tests/data/ds005365-fmriprep/sub-CISC13877/func/sub-CISC13877_task-rest_dir-AP_run-01_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt \
  integration:   tests/data/ds005365-fmriprep/sub-CISC13877/func/sub-CISC13877_task-rest_dir-AP_run-01_from-boldref_to-auto00000_mode-image_xfm.txt \
  integration:   tests/data/ds005365-fmriprep/sub-CISC13877/func/sub-CISC13877_task-rest_dir-AP_run-01_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
commands =
  pytest {posargs} \
  unit: -k 'not integration'
  integration: -k integration
runner =
  latest: uv-venv-lock-runner
pip_pre =
  pre: true
pass_env =
  PY_COLORS
  FORCE_COLOR
  NO_COLOR
  CLICOLOR
  CLICOLOR_FORCE
set_env =
  pre: PIP_EXTRA_INDEX_URL=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
  pre: UV_INDEX=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
  pre: UV_INDEX_STRATEGY=unsafe-best-match
  py3{13-15}t: PYTHONGIL={env:PYTHONGIL:0}
uv_resolution =
  min: lowest-direct

[testenv:typecheck]
extras = bids
dependency_groups =
  test
  types
runner =
  latest: uv-venv-lock-runner
commands = mypy src

[testenv:style]
deps = ruff
commands =
    ruff check .
    ruff format --diff .
