[tox]
envlist = py310, typecheck, style
isolated_build = true

[testenv]
extras = test, bids
commands = pytest {posargs}

[testenv:typecheck]
extras = test, bids
commands = mypy src

[testenv:style]
deps = ruff
commands =
    ruff check .
    ruff format --diff .
