"""EPI metadata and orientation helpers (ported from SDCFlows)."""

from __future__ import annotations

import nibabel as nb
import os

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Any


def load_api[ImgT: nb.filebasedimages.FileBasedImage](
    path: str | os.PathLike[str], api: type[ImgT]
) -> ImgT:
    img = nb.load(path)
    if not isinstance(img, api):
        raise TypeError(f'File {path} does not implement {api} interface')
    return img


# --- ensure_positive_cosines (sdcflows/utils/tools.py:133-150) ---
def ensure_positive_cosines(
    img: nb.spatialimages.SpatialImage,
) -> tuple[nb.spatialimages.SpatialImage, tuple[str, ...]]:
    """
    Reorient axes polarity to have all positive direction cosines.

    In other words, this function will reorient the image polarities to be all
    *positive*, respecting the axes ordering.
    For instance, *LAS* -> *RAS* or *ALS* -> *ARS*.

    Returns
    -------
    img : nibabel.spatialimages.SpatialImage
        Reoriented image with all positive direction cosines.
    axcodes : tuple[str, ...]
        Axis codes of the **original** image.
    """
    in_ornt = nb.io_orientation(img.affine)
    img_axcodes = nb.orientations.ornt2axcodes(in_ornt)
    out_ornt = in_ornt.copy()
    out_ornt[:, 1] = 1
    ornt_xfm = nb.orientations.ornt_transform(in_ornt, out_ornt)

    return img.as_reoriented(ornt_xfm), img_axcodes


# --- get_trt (sdcflows/utils/epimanip.py:29-295) ---
def get_trt(
    in_meta: dict,
    in_file: str | nb.spatialimages.SpatialImage | None = None,
    *,
    use_estimate: bool = False,
    fallback: float | None = None,
) -> float:
    r"""
    Obtain the *total readout time* :math:`T_\text{ro}` from available metadata.

    The following metadata fields are consulted in order:

    1. ``TotalReadoutTime`` (or ``EstimatedTotalReadoutTime`` when
       ``use_estimate=True``).
    2. Derived from ``EffectiveEchoSpacing`` (or ``EstimatedEffectiveEchoSpacing``
       when ``use_estimate=True``) multiplied by ``(N_pe - 1)``.
    3. Derived from ``EchoSpacing`` divided by ``ParallelReductionFactorInPlane``
       and multiplied by ``(N_pe // acc - 1)``.
    4. Derived from Philips ``WaterFatShift`` and ``EPIFactor`` fields.
    5. ``fallback``, if provided.
    6. Raises :obj:`ValueError` if none of the above succeeds.

    Parameters
    ----------
    in_meta : dict
        BIDS metadata dictionary.
    in_file : :class:`str` or :class:`~nibabel.spatialimages.SpatialImage`, optional
        EPI image or path to the EPI file. Used to determine the number of voxels
        along the phase-encoding direction when deriving from echo spacing.
    use_estimate : bool, optional
        Whether to use ``Estimated*`` fields to calculate the total readout time.
        These are generated by dcm2niix when authoritative metadata is not available
        but heuristic methods permit an estimation.
    fallback : float, optional
        A fallback value, in seconds, to use when the total readout time cannot be
        calculated. This should only be used in situations where the field is to be
        determined from displacement fields, as in SyN-SDC.
        A recommended "plausible" value would be 0.03125, to minimize the impact of
        floating-point errors in the calculations.

    Returns
    -------
    float
        Total readout time in seconds.

    Raises
    ------
    ValueError
        If the total readout time cannot be determined from any available field
        and no fallback is given.

    """
    # Use case 1: TRT is defined
    if 'TotalReadoutTime' in in_meta:
        return in_meta['TotalReadoutTime']
    elif use_estimate and 'EstimatedTotalReadoutTime' in in_meta:
        return in_meta['EstimatedTotalReadoutTime']

    if in_meta.keys() & {
        'PhaseEncodingDirection',
        'EffectiveEchoSpacing',
        'EstimatedEffectiveEchoSpacing',
        'EchoSpacing',
        'WaterFatShift',
    } > {'PhaseEncodingDirection'}:
        # npe = N voxels PE direction
        pe_index = 'ijk'.index(in_meta['PhaseEncodingDirection'][0])
        if in_file is None:
            raise ValueError(
                'File must be provided to determine the number of voxels along the phase-encoding direction.'
            )
        img = (
            load_api(in_file, nb.spatialimages.SpatialImage)
            if isinstance(in_file, str)
            else in_file
        )
        npe = img.shape[pe_index]

        # Use case 2: EES is defined
        ees = in_meta.get('EffectiveEchoSpacing')
        if ees:
            # Effective echo spacing means that acceleration factors have been accounted for.
            return ees * (npe - 1)
        elif use_estimate and 'EstimatedEffectiveEchoSpacing' in in_meta:
            return in_meta['EstimatedEffectiveEchoSpacing'] * (npe - 1)

        try:
            echospacing = in_meta['EchoSpacing']
            acc_factor = in_meta['ParallelReductionFactorInPlane']
        except KeyError:
            pass
        else:
            # etl = effective train length
            etl = npe // acc_factor
            return echospacing * (etl - 1)

        # Use case 3 (Philips scans)
        try:
            wfs = in_meta['WaterFatShift']
            epifactor = in_meta['EPIFactor']
        except KeyError:
            pass
        else:
            wfs_hz = (
                (in_meta.get('ImagingFrequency', 0) * 3.39941)
                or (in_meta.get('MagneticFieldStrength', 0) * 144.7383333)
                or None
            )
            if wfs_hz:
                ees = wfs / (wfs_hz * (epifactor + 1))
                return ees * (npe - 1)

    if fallback:
        return fallback

    raise ValueError('Unknown total-readout time specification')


def prepare_epi(
    img: nb.spatialimages.SpatialImage, metadata: dict[str, Any]
) -> tuple[nb.spatialimages.SpatialImage, list[tuple[int, float]]]:
    """Prepare an EPI image for resampling.

    For simplicity, the EPI image is reoriented to have all positive direction cosines.
    This function updates the PhaseEncodingDirection metadata accordingly,
    and returns the reoriented image and the corresponding phase encoding information.

    Returns
    -------
    img : :class:`~nibabel.spatialimages.SpatialImage`
        Reoriented EPI image with all positive direction cosines.
    pe_info : list[tuple[int, float]]
        A tuple of (axis-index, signed-readout-time) for each volume in the EPI image.
    """
    source, axcodes = ensure_positive_cosines(img)

    trt = get_trt(metadata, img)
    pe_dir = metadata['PhaseEncodingDirection']
    pe_axis = 'ijk'.index(pe_dir[0])

    pe_flip = pe_dir.endswith('-')
    axis_flip = axcodes[pe_axis] in 'LPI'

    pe_info: list[tuple[int, float]] = [
        (pe_axis, -trt if (axis_flip ^ pe_flip) else trt)
    ] * source.shape[3]

    return source, pe_info
