"""EPI metadata and orientation helpers (ported from SDCFlows)."""

from typing import cast

import nibabel as nb


# --- ensure_positive_cosines (sdcflows/utils/tools.py:133-150) ---
def ensure_positive_cosines(
    img: nb.spatialimages.SpatialImage,
) -> tuple[nb.spatialimages.SpatialImage, tuple[str, ...]]:
    """
    Reorient axes polarity to have all positive direction cosines.

    In other words, this interface will reorient the image polarities to be all
    *positive*, respecting the axes ordering.
    For instance, *LAS* -> *RAS* or *ALS* -> *ARS*.

    """
    in_ornt = nb.io_orientation(img.affine)
    img_axcodes = nb.orientations.ornt2axcodes(in_ornt)
    out_ornt = in_ornt.copy()
    out_ornt[:, 1] = 1
    ornt_xfm = nb.orientations.ornt_transform(in_ornt, out_ornt)

    return img.as_reoriented(ornt_xfm), img_axcodes


# --- get_trt (sdcflows/utils/epimanip.py:29-295) ---
def get_trt(
    in_meta: dict,
    in_file: str | None = None,
    *,
    use_estimate: bool = False,
    fallback: float | None = None,
) -> float:
    r"""
    Obtain the *total readout time* :math:`T_\text{ro}` from available metadata.

    BIDS provides two standard mechanisms to store the total readout time,
    :math:`T_\text{ro}`, of :abbr:`EPI (echo-planar imaging)` scans.
    The first option is that a ``TotalReadoutTime`` field is found
    in the JSON sidecar:

    Parameters
    ----------
    in_meta: :class:`dict`
        BIDS metadata dictionary.
    in_file: :class:`str`, optional
        Path to the EPI file. Used to determine the number of voxels along the
        phase-encoding direction.
    use_estimate: :class:`bool`, optional
        Whether to use "Estimated*" fields to calculate the total readout time.
        These are generated by dcm2niix when authoritative metadata is not available
        but heuristic methods permit an estimation.
    fallback: :class:`float`, optional
        A fallback value, in seconds, to use when the total readout time cannot be
        calculated. This should only be used in situations where the field is to be
        determined from displacement fields, as in SyN-SDC.
        A recommended "plausible" value would be 0.03125, to minimize the impact of
        floating-point errors in the calculations.

    """
    # Use case 1: TRT is defined
    if 'TotalReadoutTime' in in_meta:
        trt = in_meta.get('TotalReadoutTime')
        if not trt:
            raise ValueError(f"'{trt}'")

        return trt
    elif use_estimate and 'EstimatedTotalReadoutTime' in in_meta:
        trt = in_meta.get('EstimatedTotalReadoutTime')
        if not trt:
            raise ValueError(f"'{trt}'")

        return trt

    if in_meta.keys() & {
        'PhaseEncodingDirection',
        'EffectiveEchoSpacing',
        'EstimatedEffectiveEchoSpacing',
        'EchoSpacing',
        'WaterFatShift',
    } > {'PhaseEncodingDirection'}:
        # npe = N voxels PE direction
        pe_index = 'ijk'.index(in_meta['PhaseEncodingDirection'][0])
        npe = nb.load(cast(str, in_file)).shape[pe_index]  # type: ignore[attr-defined]

        # Use case 2: EES is defined
        ees = in_meta.get('EffectiveEchoSpacing')
        if ees:
            # Effective echo spacing means that acceleration factors have been accounted for.
            return ees * (npe - 1)
        elif use_estimate and 'EstimatedEffectiveEchoSpacing' in in_meta:
            return in_meta.get('EstimatedEffectiveEchoSpacing') * (npe - 1)

        try:
            echospacing = in_meta['EchoSpacing']
            acc_factor = in_meta['ParallelReductionFactorInPlane']
        except KeyError:
            pass
        else:
            # etl = effective train length
            etl = npe // acc_factor
            return echospacing * (etl - 1)

        # Use case 3 (Philips scans)
        try:
            wfs = in_meta['WaterFatShift']
            epifactor = in_meta['EPIFactor']
        except KeyError:
            pass
        else:
            wfs_hz = (
                (in_meta.get('ImagingFrequency', 0) * 3.39941)
                or (in_meta.get('MagneticFieldStrength', 0) * 144.7383333)
                or None
            )
            if wfs_hz:
                ees = wfs / (wfs_hz * (epifactor + 1))
                return ees * (npe - 1)

    if fallback:
        return fallback

    raise ValueError('Unknown total-readout time specification')
